name: Translate Episode

on:
  pull_request:
    paths:
      - "episodes/*.md"

jobs:
  translate_episode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install openai pyyaml

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Translate Markdown
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/translate_md.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Add translated episode'
          git push origin HEAD:${{ github.head_ref }}
